- name: Installing apache on webservers 
  hosts: webservers
  become: true # run as root user
  tasks:
  - name: Install apache
    yum: 
      name: httpd 
      state: present
  - name: Start the server
    service: name=httpd state=started
    # service: 
    #   name: httpd 
    #   state: started
  - name: copy file to server
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html/
    

- name: Install git on all servers
  hosts: all
  become: true
  tasks:
  - name: Install git on all servers
    package:
      name: git
      state: present
      
- name: Install wget on all servers
  hosts: all
  become: true
  tasks:
  - name: Install wget on all servers
    package: name=wget state=present

