- name: Installing apache on webservers 
  hosts: all
  become: true  
  tasks:
  - name: Install apache
    yum: 
      name: httpd 
      state: absent
  - name: Start the server
    service: name=httpd state=started
    # service: 
    #   name: httpd 
    #   state: started
  - name: copy file to server
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html/
